### ISSUE TITLE
Fabric Support Request

### ISSUE THREAD

**Issue by ColaIan** [dscalzi/Nebula#17]
Hello, I'd like to know if it would be possible to support fabric https://fabricmc.net/ in the future?

**Comment by dscalzi** [comment]
https://github.com/dscalzi/HeliosLauncher/issues/65

**Comment by ColaIan** [comment]
Do you have any clues about when approximately will it be implemented?

**Comment by dscalzi** [comment]
All the information available is on the issue/linked issue. Probably not in the immediate future.

**Comment by moehreag** [comment]
Hello, I'd like to know if this could be implemented now. I decided to ask again because it's now

> technically possible to support
(quote from 28 days ago, https://github.com/dscalzi/HeliosLauncher/issues/65#issuecomment-882266052)

I for myself am too dumb to do it or write a distribution.json by hand. If I can help achieving this, let me know. I'll do anything possible for me to contribute to this goal.
