### ISSUE TITLE
no gui for recent forge versions

### ISSUE THREAD

**Issue by lukruh** [dscalzi/Nebula#5]
Hey, 
I tried to follow the readme to create an own distribution.json for my server. It worked for older mc versions (like 1.12.2 from the example), but when I try to generate distro for 1.15.2 version (forge 31) it fails (missing server meta) and warns about no DISPLAY variable which is probably required to run forge installer. Is there something like a command line only solution?
Cheers Lukruh 

PS: I don't want to be picky, but as a node beginner it took me some time to figure out, that the command actually should be `generate distro` while the example in the readme says: `generate distribution`.

**Comment by lukruh** [comment]
I run the installation process locally and this is the window that causes the problem on headless server.
![image](https://user-images.githubusercontent.com/7965770/80805030-2ee11380-8bb7-11ea-95ea-45e898d96753.png)

**Comment by dscalzi** [comment]
There is no way to automate the client installation without the GUI. The forge developers refuse to add a command line option to run a client install because they want people to download the installer from their download page, in turn generating ad revenue. A rough quote is that they want to make it "as inconvenient as possible" to automate any portion of the client installation.

Unfortunately there's no solution other than generating everything on your local machine (or a non headless server), and then moving the files to where you want them. Note that this only applies to 1.13+, as 1.12.2 and below do not require us to pull files that the forge installer generates.

**Comment by lukruh** [comment]
Ok, thanks for the quick reply :)
